package com.example.servingwebcontent.controller;

import com.example.servingwebcontent.Incontro;
import com.example.servingwebcontent.entity.User;
import com.example.servingwebcontent.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;


import javax.servlet.http.HttpSession;

@Controller
// This means URL's start with /myapp (after Application path)
@RequestMapping(path="/myapp")
public class UserControllerMVC {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	public Incontro match;

	@GetMapping("/login")
	public  String login(Model model, HttpSession session) {
		match.resetBoard();
		return "login";
	}

	@GetMapping("/playground")
	public  String login(
			@RequestParam(name="id", required=false, defaultValue= "1")
					Integer id, Model model) {

		User u = userRepository.getById(id);
		String symbol = "";
		String action = "";

		if (match.getNumberOfPlayer()==2)
			return "nomoregamer";

		if (match.getNumberOfPlayer()==0) {
			symbol = "X";
			action = "Attendi il tuo avversario";
			match.setU1(u);
			match.setNumberOfPlayer(1);
		} else {
			symbol = "O";
			action = "Attendi il tuo turno";
			match.setU2(u);
			match.setNumberOfPlayer(2);
			match.setPlayerTurn(match.getU1().getId());
		}

		Integer mappa[][] = new Integer[3][3];
		int idBtn = 1;
		for (int i =0; i<3; i++)
			for (int j =0; j<3; j++) {
				mappa[i][j] = idBtn;
				idBtn++;
			}


		model.addAttribute("mappa", mappa);
		model.addAttribute("name", u.getName());
		model.addAttribute("userId", u.getId());
		model.addAttribute("symbol", symbol);
		model.addAttribute("action", action);
		return "playground";
	}

}
